# Generated by Django 3.1.4 on 2021-03-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210313_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference_number',
            field=models.CharField(blank=True, default='3150104165', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='item_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
