# Generated by Django 3.1.4 on 2021-03-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210314_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='g_price',
            new_name='beverage_g_price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='s_price',
            new_name='beverage_s_price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='t_price',
            new_name='beverage_t_price',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='v_price',
            new_name='beverage_v_price',
        ),
        migrations.AddField(
            model_name='item',
            name='cake_size',
            field=models.CharField(blank=True, choices=[('SLICE', 'SLICE'), ('WHOLE', 'WHOLE')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='cake_slice_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='cake_whole_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='reference_number',
            field=models.CharField(blank=True, default='8713564424', max_length=10, null=True, unique=True),
        ),
    ]
