# Generated by Django 3.1.4 on 2021-03-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210314_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference_number',
            field=models.CharField(blank=True, default='4535650695', max_length=10, null=True, unique=True),
        ),
    ]
