# Generated by Django 3.1.4 on 2021-03-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210314_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='reference_number',
            field=models.CharField(blank=True, default='5468771163', max_length=10, null=True, unique=True),
        ),
    ]
