# Generated by Django 3.1.4 on 2021-03-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210314_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='categories',
            new_name='category',
        ),
        migrations.AlterField(
            model_name='order',
            name='reference_number',
            field=models.CharField(blank=True, default='3471077910', max_length=10, null=True, unique=True),
        ),
    ]
