# Generated by Django 3.1.4 on 2021-03-15 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210314_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='cake_size',
            field=models.CharField(blank=True, choices=[('SLICE', 'SLICE'), ('WHOLE', 'WHOLE')], default='SLICE', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='sizes',
            field=models.CharField(blank=True, choices=[('Short', 'Short'), ('Tall', 'Tall'), ('Grande', 'Grande'), ('Venti', 'Venti')], default='Short', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='reference_number',
            field=models.CharField(blank=True, default='8800939874', max_length=10, null=True, unique=True),
        ),
    ]
